# Site settings
baseURL = "https://jewelshousesitting.com"
languageCode = "en-US"
title = "Jewel's Housesitting"
theme = "split"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Local preview mode
relativeURLs = true
uglyURLs = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2022 Jewel Weed"

[params]

  # Metadata for search engines and social sharing
  author = "Jewel Weed"
  description = "When you go on vacation, who watches your animals? The most common pet sitter is a family member or close friend, but what if they're unable to watch your animal or don't feel comfortable doing so?"
  shareImage = "images/animals.jpg"
  twitterHandle = "#"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/jewel.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      # file = "videos/background.mp4"
      youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:jewel.lynn2000@gmail.com"

      [[params.links.list1.link]]
        text = "Call"
        url = "tel:"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Facebook"
        url = "https://www.facebook.com/112741744739859/posts/112744351406265"



  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
