name: Build and Deploy (CI/CD)

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/deploy.yml'
      - 'public/**'
      - 'res/**'
      - 'next.config.js'
      - 'src/**'
      - 'yarn.lock'
      - 'package.json'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-deploy:
    name: Build and Deploy (CI/CD)
    runs-on: ubuntu-latest
    env:
      s3-bucket:    'jewelshousesitting.com'
      node-version: '16.x'

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - uses: c-hive/gha-yarn-cache@v2
      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:      ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:             us-west-1

      - name: Deploy to S3
        run: aws s3 sync ./out/ s3://${{ env.s3-bucket }} --delete
