name: Build and Deploy (CI/CD)

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/deploy.yml'
      - 'res/**'
      - 'src/**'
  workflow_dispatch:

jobs:
  build-deploy:
    name: Build and Deploy (CI/CD)
    runs-on: ubuntu-latest
    env:
      s3-bucket: 'jewelshousesitting.com'
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/checkout@v2
        with:
          path: 'src/themes/split'
          repository: 'robert-clayton/hugo-split-theme'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2

      - name: Build Hugo example site
        run: cd src && hugo -v

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:      ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:             us-west-1

      - name: Deploy to S3
        run: aws s3 sync ./src/public/ s3://${{ env.s3-bucket }} --delete

      - name: Deploy to CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*' 
